version: "3.8"
services:
  mysql-database:
    build: ./mysql-database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Roter12
      MYSQL_DATABASE: test_database
    restart: always
    ports: 
      - "3306:3306"
  web-nodejs:
    build: ./web-nodejs
    restart: always
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Roter12
      MYSQL_HOST: mysql-database
      GOOGLE_CLIENT_ID: 509185347493-siql3qg04kjdbagcmnkce5ql791djk7a.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      PORT: 3000
    ports:
      - "3000:3000"
